### ISSUE TITLE
NameError: global name 'rvname' is not defined

### ISSUE THREAD

**Issue by ByReaL** [mvz/vb2py#1]
```
Traceback (most recent call last):
  File "c:\Python27\Lib\site-packages\vb2py\app.py", line 681, in <module>
    main()
  File "c:\Python27\Lib\site-packages\vb2py\app.py", line 627, in main
    renderTo(conv, destination_dir, do_code)
  File "c:\Python27\Lib\site-packages\vb2py\app.py", line 652, in renderTo
    item.writeToFile(destination_dir, do_code)
  File "c:\Python27\Lib\site-packages\vb2py\app.py", line 543, in writeToFile
    fle.write(vbparser.renderCodeStructure(self.code_structure))
  File "c:\Python27\lib\site-packages\vb2py\vbparser.py", line 179, in renderCodeStructure
    return applyPlugins("postProcessPythonText", structure.renderAsCode())
  File "c:\Python27\lib\site-packages\vb2py\parserclasses.py", line 1114, in renderAsCode
    declarations = self.renderDeclarations(indent + self.indent_all_blocks)
  File "c:\Python27\lib\site-packages\vb2py\parserclasses.py", line 1157, in renderDeclarations
    ret.append(declaration.renderAsCode(indent))
  File "c:\Python27\lib\site-packages\vb2py\parserclasses.py", line 2154, in renderAsCode
    block = self.block.renderAsCode(indent + 1)
  File "c:\Python27\lib\site-packages\vb2py\parserclasses.py", line 534, in renderAsCode
    return "".join([block.renderAsCode(indent) for block in self.blocks])
  File "c:\Python27\lib\site-packages\vb2py\parserclasses.py", line 2212, in renderAsCode
    ret += self.if_block.renderAsCode(indent + 1)
  File "c:\Python27\lib\site-packages\vb2py\parserclasses.py", line 534, in renderAsCode
    return "".join([block.renderAsCode(indent) for block in self.blocks])
  File "c:\Python27\lib\site-packages\vb2py\parserclasses.py", line 1748, in renderAsCode
    return "%sreturn %s\n" % (indenter, rvname)
NameError: global name 'rvname' is not defined
```

**Comment by mvz** [comment]
Fixed in #2, thanks!
